apiVersion: v1
kind: Service
metadata:
   name: clusteripservice
   namespace: ndeploy
   
spec:

  type: ClusterIP
  selector:
    tier: pythonapp

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000   

