apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod

spec:
 containers:
  - name: nginx-cont
    image: nginx
    volumeMounts:
     - name: pvc-volumes
       mountPath: /usr/share/nginx/html  

 volumes:
   - name: pvc-volumes
     persistentVolumeClaim:
      claimName: p-v-claim   
 
 affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - desktop-worker       
